name: Create Release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build extension
        run: npm run package

      - name: Create versioned vsix file
        run: |
          # The package command creates folder-duplicator-{version}.vsix
          # Rename to folder-duplicator.vsix and create versioned copy
          mv folder-duplicator-${{ steps.get_version.outputs.VERSION }}.vsix folder-duplicator.vsix
          cp folder-duplicator.vsix folder-duplicator_v${{ steps.get_version.outputs.VERSION }}.vsix

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ steps.get_version.outputs.VERSION }} \
            --title "v${{ steps.get_version.outputs.VERSION }}" \
            --target ${{ github.ref_name }} \
            --generate-notes \
            --draft \
            folder-duplicator.vsix \
            folder-duplicator_v${{ steps.get_version.outputs.VERSION }}.vsix
